name: SMARTS CI Header Test

on: [push]

env:
  venv_dir: .venv
jobs:
  test-header:
    runs-on: ubuntu-18.04
    container: huaweinoah/smarts:v0.4.3-pre
    steps:
      - name: test header
      run: |
        make header-test
